require_relative './config/environment'

# these are helper rake tasks
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  Pry.start
end

desc "Says hello to the cohort"
task :hellocohort do
  puts "Hello nyc-mhtn-web-040218"
end
